sudo: required 
dist: trusty 
language: generic 
compiler:
  - gcc
notifications:
  email:
    on_success: always
    on_failure: always
#    recipients:
#      - jane@doe
env:
  global:
    - VERBOSE_OUTPUT=true
  matrix:
    - COVERALLS_REPO_TOKEN="9E7mHUiU8AKT0MXy8Q0XJJoWTc7OOJ0ix" ROS_CI_COVERAGE=true USE_DEB=true ROS_DISTRO="kinetic" ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu AFTER_SCRIPT='source /root/catkin_ws/devel/setup.bash && cd /root/catkin_ws/build/intelli_bot && make coveralls'
    #- USE_DEB=true  ROS_DISTRO="kinetic"   ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu
matrix:
  allow_failures:
    #- env: USE_DEB=true  ROS_DISTRO="kinetic"   ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu
install:
  - git clone --depth 1 https://github.com/ros-industrial/industrial_ci.git .ci_config
  - cd /root/catkin_ws/src
  - git clone https://github.com/angelsantamaria/tum_simulator.git
  - git clone https://github.com/AutonomyLab/ardrone_autonomy.git -b indigo-devel

before_script:
  - echo ROS_CI_COVERAGE >> .ci_config/industrial_ci/src/docker.env
  - echo COVERALLS_REPO_TOKEN >> .ci_config/industrial_ci/src/docker.env
  - echo TRAVIS_JOB_ID >> .ci_config/industrial_ci/src/docker.env
  
script: 
  - source .ci_config/travis.sh
#  - source ./travis.sh  # Enable this when you have a package-local script 

#  vim: set et fenc=utf-8 ff=unix sts=0 sw=2 ts=2 : 
