sudo: required 
dist: trusty 
language: generic 
compiler:
  - gcc
addons:
  apt:
    packages:
     - libsuitesparse-dev
     - libqglviewer-dev-qt4
     - ros-kinetic-libg2o
     - ros-kinetic-opencv3 
notifications:
  email:
    on_success: always
    on_failure: always
#    recipients:
#      - jane@doe
env:
  global:
    # - VERBOSE_OUTPUT=false
  matrix:
    - COVERALLS_REPO_TOKEN="9E7mHUiU8AKT0MXy8Q0XJJoWTc7OOJ0ix" ROS_CI_COVERAGE=true ROS_DISTRO="kinetic" ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu AFTER_SCRIPT='source /root/catkin_ws/devel/setup.bash && cd /root/catkin_ws/build/intelli_bot && make coveralls'  UPSTREAM_WORKSPACE=file ROSINSTALL_FILENAME=extern_depends.rosinstall 
    #- USE_DEB=true  ROS_DISTRO="kinetic"   ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu
matrix:
  allow_failures:
    #- env: USE_DEB=true  ROS_DISTRO="kinetic"   ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu
install:
  - sudo apt-get install libsuitesparse-dev libqglviewer-dev-qt4 ros-kinetic-libg2o  ros-kinetic-opencv3
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libQGLViewer-qt4.so /usr/lib/x86_64-linux-gnu/libQGLViewer.so
  - git clone --depth 1 https://github.com/ros-industrial/industrial_ci.git .ci_config

before_script:
  - echo ROS_CI_COVERAGE >> .ci_config/industrial_ci/src/docker.env
  - echo COVERALLS_REPO_TOKEN >> .ci_config/industrial_ci/src/docker.env
  - echo TRAVIS_JOB_ID >> .ci_config/industrial_ci/src/docker.env
  
script: 
  - source .ci_config/travis.sh

#  - source ./travis.sh  # Enable this when you have a package-local script 

#  vim: set et fenc=utf-8 ff=unix sts=0 sw=2 ts=2 : 
